[package]
name = "bt_anytype_map"
version = "0.1.0"
edition = "2024"
authors = ["calvarez <calvarez@bachuetech.biz>"]
description = "Basic HashMap to store any data type in a thread-safe manner with zero dependencies"
keywords = ["hashmap","any_type"]
categories = ["data-structures", "caching"]
repository = "https://github.com/bachuetech/bt_anytype_map.git"
readme = "README.md"
homepage = "https://github.com/bachuetech/bt_anytype_map"
license = "GPL-3.0-only"

[dependencies]


[dev-dependencies]
tokio = { version = "1.52.3", features = ["macros", "rt-multi-thread"] }
moka = {version="0.12.15", features = ["future"] }
